### PR TITLE
Upgrade to sap/cds 3

### PR DESCRIPTION
**Pull request by xtough**
@chgeo FYI

### CODE REVIEW

**Comment by chgeo** [comment]
Looks good for me.

Please adjust sap/cds dependency to `^3.5` as it wouldn't work with lower versions like 3.4.1.\
I will merge it as soon as 3.5.0 is out.

**Comment by xtough** [comment]
@chgeo Why shall I bump the dependency? The build tasks just won't do any harm prior to cds 3.5

**Comment by chgeo** [comment]
Yes, they do.  They fail with 3.4.1 ;)

**Review by xtough — COMMENTED** [review]
@chgeo some more fine-tuning for 3.x

**Review by LotharBender — CHANGES_REQUESTED** [review]
add missing task for ui module build:
          {"src":"ui","for":"fiori","options":{"model":["db","srv","ui"]}}

...as discussed with Christian skip this for now as fiori build currently only supports data source 'mainService' as generated by fiori webide wizard

**Pull request merged**
